# The name of this site
# This text displays in the back-office and 
# can be used in templates through the site.name global variable
name: LocomotiveCMS

# The site's subdomain
# This option is for sites on multi-site engines
# The value determines where the site can be accessed under the engine's primary domain
# subdomain: sample

# An array of domain aliases for the site
# This option is for sites on multi-site engines
# domains: [www.example.com, example.com]

# An array of locales (languages) the site is available in
# The locale listed first is the site's default locale
# Locales are specified using ISO language codes
# Possible locales include: en, de, fr, pl, pt-BR, it, nl, nb, es, ru, et, ja, zh-CN
locales: [en]

# The site's timezone
# This converts the server's time to the site's time zone in templates
# The TimeZone class from Rail's ActiveSupport is used to interpret the string
# Sample timezone strings: Tokyo, Beijing, Moscow, Cairo, Paris, Pacific Time (US & Canada)
# timezone: Paris

# For SEO purposes, sites may wish to add a relevant string to the <title> tag
# And include <meta type="keywords"> and <meta type="description">
# For this purpose you can set values for these variables here
# They can be accessed in templates through the site.seo_title, site.meta_keywords, and site.meta_description variables
seo_title: LocomotiveCMS is an open source CMS for Rails
meta_description: LocomotiveCMS is a free open source CMS in Rails that helps web developers create and manage websites faster than ever.
meta_description: "cms open source ruby on rails heroku liquid rails3 cloud amazon S3 inline editing"